steps: 
- name: node:16.13.1
  entrypoint: npm
  args: ["install"]
- name: node:16.13.1
  entrypoint: npm
  args: ["create-env", "start"]
  env:
    - 'COOKIE_SECRET=${_COOKIE_SECRET}'
    - 'HOST=${_HOST}'
    - 'SEQUELIZE_PASSWORD=${_SEQUELIZE_PASSWORD}'
    - 'USERNAME=${_USERNAME}'
timeout: "1600s"